# Generated by Django 5.0.3 on 2024-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_workshopsummary_psychologist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
