# Generated by Django 5.0.2 on 2024-04-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_babyhealth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comments',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
    ]
