# Generated by Django 5.0.3 on 2024-04-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_pediatricianinfoboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traking',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.parent')),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
            bases=('account.parent',),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.parent')),
            ],
        ),
    ]
