# Generated by Django 5.0.4 on 2024-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_paropinion_delete_feedback2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshopped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('link', models.URLField()),
            ],
        ),
    ]
