# Generated by Django 3.0.14 on 2024-04-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20240408_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workshop',
        ),
    ]
