# Generated by Django 3.0.14 on 2024-04-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_delete_workshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParentProfile',
        ),
    ]
