# Generated by Django 3.0.14 on 2024-04-08 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0019_auto_20240408_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='challenges',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='parent',
            name='child_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='child_gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='PediatricianId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
