# Generated by Django 5.0.3 on 2024-04-09 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_parentn_remove_parent_challenges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='parentN',
        ),
        migrations.RemoveField(
            model_name='psychologistn',
            name='user',
        ),
        migrations.AddField(
            model_name='parent',
            name='challenges',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='parent',
            name='child_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parent',
            name='child_gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='parent',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='parent',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='parent',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pediatrician',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='specialization',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='psychologist',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='pediatricianN',
        ),
        migrations.DeleteModel(
            name='psychologistN',
        ),
    ]
